apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inbox-zero-ingress
  namespace: inbox-zero
spec:
  rules:
  - host: inbox-zero.local
    http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: inbox-zero-web
              port:
                number: 80

