apiVersion: v1
kind: Service
metadata:
  name: anything-llm-svc
  namespace: anything-llm
spec:
  selector:
    app: anything-llm
  type: NodePort
  ports:
  - name: anything-llm-svc
    protocol: TCP 
    port: 3001
    targetPort: 3001
    nodePort: 32001
---

